"""
    Copyright (C) 2015 Colorbleed Studios.
    All rights reserved.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND. COLORBLEED
    STUDIOS DOES NOT MAKE AND HEREBY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTIES
    INCLUDING, BUT NOT LIMITED TO, THE WARRANTIES OF NON-INFRINGEMENT,
    MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE
    OF DEALING, USAGE, OR TRADE PRACTICE. IN NO EVENT WILL COLORBLEED STUDIOS
    BE LIABLE FOR ANY LOST REVENUES, DATA, OR PROFITS, OR SPECIAL,
    DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES, EVEN IF COLORBLEED STUDIOS
    HAS BEEN ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES.

    http://www.colorbleed.nl/

    @date: December 14th, 2014
    @version: 0.2.1
    @author: Roy Nieterau (roy@colorbleed.nl)
"""

from version import *

__author__ = "Roy Nieterau"
__all__ = ['core', 'datatypes']